name: Build and upload

on:
  release:
    types: [published]

jobs:
  build:

    strategy:
      matrix:
        python-version: [ 3.8 ]
        os-version: [ windows-latest ]

    runs-on: ${{ matrix.os-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pyinstaller
        run: |
          pyinstaller UPCNet.py

      - name: Stash dist to artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  upload:
    needs: [build]

    strategy:
      matrix:
        os-version: [ ubuntu-latest ]

    runs-on: ${{ matrix.os-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Download dist from artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: UPCNet

      - name: Zip file
        run: |
          mv UPCNet/UPCNet UPCNet/bin
          zip -r upcnet-windows.zip UPCNet

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: upcnet-windows.zip application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
